{{- range .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .app_name }}
  namespace: argocd
spec:
  destination:
    namespace: {{ default .app_name .namespace }}
    server: https://kubernetes.default.svc
  project: {{ .app_name }}
  source:
    path: "helm"
    repoURL: git@github.com:camfu-co/hl_helm.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - {{ .app_name }}.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}